name             'berkshelf'
maintainer       'James FitzGibbon'
maintainer_email 'james@nadt.net'
license          'All rights reserved'
description      'Installs berkshelf'
version          '0.1.2'
depends          'cligem'
depends          'rbenv', '~> 0.7'
depends          'ruby_build', '~> 0.8'

